apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
      - name: quote-api-container
        # IMPORTANT: Use your Docker Hub username here
        image: sudlo/quote-api:latest
        ports:
        - containerPort: 8080
